/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnaMenu;

import Grup.GrupNavigasyon;
import Grup.YeniGrupOlustur;
import Kasa.kasaKayit;
import Kasa.senetOdeme;
import MailGonderme.MailForm;
import OgrenciKayit.KayitYonlendirme;
import Rehberlik.OgrenciDersProgramiOlustur;
import Rehberlik.Rehberlik;
import Rehberlik.Rehberlik;
import Scanner.Tarama;
import hizliArama.arama;
import java.awt.Color;
import kullanici.kontrol;
import kullanici.kullaniciHesaplari;
import personel.personelKayit;
import yedekleme.yedekleme;
import yedekleme.yedeklemeEkran;

/**
 *
 * @author java2
 */
public class Menu extends javax.swing.JFrame {

    kontrol kontrol = new kontrol();

    public Menu() {
        initComponents();
        //arama
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(false);
        jButton8.setFocusable(false);
        
        //mail
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(false);
        jButton4.setFocusable(false);
        //muhasebe
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(false);
        jButton7.setFocusable(false);
        //kullanıcı
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(false);
        jButton5.setFocusable(false);
          //öğrenci
        jButton10.setContentAreaFilled(false);
        jButton10.setOpaque(false);
        jButton10.setFocusable(false);
          //tarayıcı
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(false);
        jButton6.setFocusable(false);
          //personel
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.setFocusable(false);
         //yedekle
        jButton9.setContentAreaFilled(false);
        jButton9.setOpaque(false);
        jButton9.setFocusable(false);
         //grup
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.setFocusable(false);
         //rehberlik
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(false);
        jButton3.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466133282_Group_Meeting_Light.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 220, 120, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466132495_-23.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 127, 135, 135));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466135019_compass.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 130, 130));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466134706_message-already-read.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 282, 90, 80));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anaekranKULLANICI.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 140, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466132180_scanner.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 397, 115, 120));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466134596_cashbox.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 335, 130, 110));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466132713_cmyk-03.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 505, 119, 125));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1466135380_Student-3.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 307, 180, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anaekranARAMA.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setDisabledIcon(null);
        jButton8.setDisabledSelectedIcon(null);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 405, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/White-Background-9B1_kucuk.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1225, 815));
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Grup.GrupNavigasyon grup = new GrupNavigasyon();
        grup.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        personel.personelKayit person = new personelKayit();
        person.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int button_id = 7;

        if (kontrol.kontrol(button_id)) {

          Rehberlik rehberlik=new Rehberlik();
            rehberlik.setVisible(true);
            this.setVisible(false);

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int button_id = 12;
        if (kontrol.kontrol(button_id)) {
            Scanner.Tarama st = new Tarama();
            st.pdfReader();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int button_id = 8;

        if (kontrol.kontrol(button_id)) {
            MailGonderme.MailForm mail = new MailForm();
            mail.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       

muhasebe2 muh=new muhasebe2();
muh.setVisible(true);
this.setVisible(false);


        


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        kullanici.kullaniciHesaplari hesaplari = new kullaniciHesaplari();
        hesaplari.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int button_id = 15;

        if (kontrol.kontrol(button_id)) {
            yedeklemeEkran yedek = new yedeklemeEkran();
            yedek.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int button_id = 16;

        if (kontrol.kontrol((button_id))) {
            OgrenciKayit.KayitYonlendirme kayitYonlendirme = new KayitYonlendirme();
            kayitYonlendirme.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        arama ar = new arama();
        ar.setVisible(true);
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
