//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajOtomasyon {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Ayar_Veritabani : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ayar_Veritabani defaultInstance = ((Ayar_Veritabani)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ayar_Veritabani())));
        
        public static Ayar_Veritabani Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string veritabani {
            get {
                return ((string)(this["veritabani"]));
            }
            set {
                this["veritabani"] = value;
            }
        }
    }
}
